name: honeycomb
repository: https://github.com/AlexanderFarkas/honeycomb

packages:
  - packages/**
  - examples/**

command:
  bootstrap:
    usePubspecOverrides: true
  
scripts:
  test:
    exec: dart test    