name: honeycomb_flutter
description: Flutter wrapper around honeycomb
version: 0.1.0

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=3.0.0"
  

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
