name: honeycomb_flutter
description: honeycomb for Flutter
version: 0.8.0+3
repository: https://github.com/AlexanderFarkas/honeycomb/tree/master/packages/honeycomb_flutter

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=3.0.0"
  

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  honeycomb: ^0.9.1
  meta: ^1.7.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
