name: honeycomb_flutter
description: Flutter wrapper around honeycomb
version: 0.2.2
repository: https://github.com/AlexanderFarkas/honeycomb/tree/master/packages/honeycomb_flutter

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=3.0.0"
  

dependencies:
  flutter:
    sdk: flutter
  honeycomb: ^0.3.1
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
