name: honeycomb
description: Smart Service Locator.
version: 0.2.0+1
repository: https://github.com/AlexanderFarkas/honeycomb/tree/master/packages/honeycomb

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  meta: ^1.8.0

