name: honeycomb
description: Smart IoC Container.
version: 0.1.1+2

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  fast_immutable_collections: ^7.4.1
  meta: ^1.8.0

