name: honey_bloc
description: honeycomb wrapper for bloc package
repository: https://github.com/AlexanderFarkas/honeycomb/tree/master/packages/honey_bloc
version: 0.3.0+2

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  honeycomb_flutter: ^0.6.0+2
  bloc: ^8.1.0
  nested: ^1.0.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
