name: honey_bloc
description: A starting point for Dart libraries or applications.
version: 0.1.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  honeycomb_flutter: ^0.4.0
  bloc: ^8.1.0
  nested: ^1.0.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
